DELETE FROM APM_SUBSCRIPTION ;
DELETE FROM APM_APPLICATION ;
DELETE FROM APM_SUBSCRIBER;
DELETE FROM APM_APP;
DELETE FROM IDN_OAUTH2_ACCESS_TOKEN ;
DELETE FROM IDN_OAUTH_CONSUMER_APPS;

ALTER TABLE APM_SUBSCRIBER ALTER COLUMN SUBSCRIBER_ID RESTART WITH 1;
ALTER TABLE APM_APPLICATION ALTER COLUMN APPLICATION_ID RESTART WITH 100;
ALTER TABLE APM_APP ALTER COLUMN APP_ID RESTART WITH 500;
ALTER TABLE APM_SUBSCRIPTION ALTER COLUMN SUBSCRIPTION_ID RESTART WITH 1000;

INSERT INTO APM_SUBSCRIBER ( USER_ID , TENANT_ID , EMAIL_ADDRESS , DATE_SUBSCRIBED ) VALUES ('SUMEDHA',-1234,'SUMEDHA@WSO2.COM','2012-03-05 12:10:11');
INSERT INTO APM_SUBSCRIBER ( USER_ID , TENANT_ID , EMAIL_ADDRESS , DATE_SUBSCRIBED ) VALUES ('PRABATH',-1234,'PRABATH@WSO2.COM','2012-03-05 12:10:11');
INSERT INTO APM_SUBSCRIBER ( USER_ID , TENANT_ID , EMAIL_ADDRESS , DATE_SUBSCRIBED ) VALUES ('THILINA',-1234,'THILINA@WSO2.COM','2012-03-05 12:10:11');
INSERT INTO APM_SUBSCRIBER ( USER_ID , TENANT_ID , EMAIL_ADDRESS , DATE_SUBSCRIBED ) VALUES ('UDAYANGA',-1234,'UDAYANGA@WSO2.COM','2012-03-05 12:10:11');


INSERT INTO APM_APPLICATION  (NAME,SUBSCRIBER_ID ) VALUES ('APPLICATION1',1);
INSERT INTO APM_APPLICATION  (NAME,SUBSCRIBER_ID ) VALUES ('APPLICATION2',1);
INSERT INTO APM_APPLICATION  (NAME,SUBSCRIBER_ID ) VALUES ('APPLICATION3',2);
INSERT INTO APM_APPLICATION  (NAME,SUBSCRIBER_ID ) VALUES ('APPLICATION4',2);
INSERT INTO APM_APPLICATION  (NAME,SUBSCRIBER_ID ) VALUES ('APPLICATION5',3);
INSERT INTO APM_APPLICATION  (NAME,SUBSCRIBER_ID ) VALUES ('DeliciousApp',4);

INSERT INTO APM_APP (APP_PROVIDER,APP_NAME,APP_VERSION,CONTEXT) VALUES ('SUMEDHA', 'API1', 'V1.0.0','/context1');
INSERT INTO APM_APP (APP_PROVIDER,APP_NAME,APP_VERSION,CONTEXT) VALUES ('PRABATH', 'API2', 'V1.0.0','/deli2');
INSERT INTO APM_APP (APP_PROVIDER,APP_NAME,APP_VERSION,CONTEXT) VALUES ('ADMIN', 'API3', 'V1.0.0','/test');
INSERT INTO APM_APP (APP_PROVIDER,APP_NAME,APP_VERSION,CONTEXT) VALUES ('DEL', 'Delicious', '1.0.0','/deli');

INSERT INTO APM_SUBSCRIPTION  ( TIER_ID , APP_ID , APPLICATION_ID , LAST_ACCESSED, SUB_STATUS ) VALUES ('T1',500,100,'2012-03-05 12:10:11','ACTIVE');
INSERT INTO APM_SUBSCRIPTION  ( TIER_ID , APP_ID , APPLICATION_ID , LAST_ACCESSED, SUB_STATUS ) VALUES ('T1',501,101,'2012-03-05 12:10:11','ACTIVE');
INSERT INTO APM_SUBSCRIPTION  ( TIER_ID , APP_ID , APPLICATION_ID , LAST_ACCESSED, SUB_STATUS ) VALUES ('T1',500,102,'2012-03-05 12:10:11','ACTIVE');
INSERT INTO APM_SUBSCRIPTION  ( TIER_ID , APP_ID , APPLICATION_ID , LAST_ACCESSED, SUB_STATUS ) VALUES ('T1',502,103,'2012-03-05 12:10:11','ACTIVE');
INSERT INTO APM_SUBSCRIPTION  ( TIER_ID , APP_ID , APPLICATION_ID , LAST_ACCESSED, SUB_STATUS ) VALUES ('T1',501,104,'2012-03-05 12:10:11','ACTIVE');
INSERT INTO APM_SUBSCRIPTION  ( TIER_ID , APP_ID , APPLICATION_ID , LAST_ACCESSED, SUB_STATUS ) VALUES ('T1',503,105,'2012-03-05 12:10:11','ACTIVE');
INSERT INTO APM_SUBSCRIPTION  ( TIER_ID , APP_ID , APPLICATION_ID , LAST_ACCESSED, SUB_STATUS ) VALUES ('T1',501,102,'2012-03-05 12:10:11','ACTIVE');

INSERT INTO IDN_OAUTH_CONSUMER_APPS ( APP_NAME , CALLBACK_URL , CONSUMER_KEY , CONSUMER_SECRET ,OAUTH_VERSION , TENANT_ID , USERNAME ) VALUES (NULL,NULL,'CON1','MY PEN','2.0',0,'PRABATH');
INSERT INTO IDN_OAUTH_CONSUMER_APPS ( APP_NAME , CALLBACK_URL , CONSUMER_KEY , CONSUMER_SECRET ,OAUTH_VERSION , TENANT_ID , USERNAME ) VALUES (NULL,NULL,'CON2','MY PEN','2.0',0,'PRABATH');
INSERT INTO IDN_OAUTH_CONSUMER_APPS ( APP_NAME , CALLBACK_URL , CONSUMER_KEY , CONSUMER_SECRET ,OAUTH_VERSION , TENANT_ID , USERNAME ) VALUES (NULL,NULL,'CON3','MY PEN','2.0',0,'admin');

INSERT INTO IDN_OAUTH2_ACCESS_TOKEN ( ACCESS_TOKEN ,AUTHZ_USER , USER_TYPE , CONSUMER_KEY , REFRESH_TOKEN ,TIME_CREATED , TOKEN_SCOPE , TOKEN_STATE ,VALIDITY_PERIOD ) VALUES ('a1b2c3d4','UDAYANGA','DEVELOPER','CON1',NULL,'2012-01-01','SANDBOX','ACTIVE',1343714931875);
INSERT INTO IDN_OAUTH2_ACCESS_TOKEN ( ACCESS_TOKEN ,AUTHZ_USER , USER_TYPE , CONSUMER_KEY , REFRESH_TOKEN ,TIME_CREATED , TOKEN_SCOPE , TOKEN_STATE ,VALIDITY_PERIOD ) VALUES ('p1q2r3s4','RUWAN','DEVELOPER','CON1',NULL,'2012-01-01','PRODUCTION','ACTIVE',1343714931875);
INSERT INTO IDN_OAUTH2_ACCESS_TOKEN ( ACCESS_TOKEN ,AUTHZ_USER , USER_TYPE , CONSUMER_KEY , REFRESH_TOKEN ,TIME_CREATED , TOKEN_SCOPE , TOKEN_STATE ,VALIDITY_PERIOD ) VALUES ('test1','NUWAN','DEVELOPER','CON1',NULL,'2012-01-01','PRODUCTION','ACTIVE',1343714931875);
INSERT INTO IDN_OAUTH2_ACCESS_TOKEN ( ACCESS_TOKEN ,AUTHZ_USER , USER_TYPE , CONSUMER_KEY , REFRESH_TOKEN ,TIME_CREATED , TOKEN_SCOPE , TOKEN_STATE ,VALIDITY_PERIOD ) VALUES ('test2','UDAYANGA','DEVELOPER','CON2',NULL,'2012-01-01','SANDBOX','ACTIVE',1343714931875);
INSERT INTO IDN_OAUTH2_ACCESS_TOKEN ( ACCESS_TOKEN ,AUTHZ_USER , USER_TYPE , CONSUMER_KEY , REFRESH_TOKEN ,TIME_CREATED , TOKEN_SCOPE , TOKEN_STATE ,VALIDITY_PERIOD ) VALUES ('test3','UDAYANGA','DEVELOPER','CON3',NULL,'2012-01-01','PRODUCTION','ACTIVE',3600);

SELECT * FROM APM_SUBSCRIBER;
SELECT * FROM APM_APPLICATION;
SELECT * FROM APM_SUBSCRIPTION;
